const simData=[
    {
      srNo:1,
      collegeCode:'',
      stuName:"",
      simuName:"Tyro Learning  (Advance E-learning Portal)",
      discription:'Shivam Shukla , Lavish Chaddha , Kanhaiya Agrawal , Devarshi Gupta',
      ref:'http://greenindia.store/learning',
      stuPic:'../imgs/user.png',
      CprgType:true,
    },
    {
        srNo:2,
        collegeCode:'',
        stuName:"",
        simuName:"Resume Builder",
        discription:'Aman Kumar',
        ref:'https://resume-builder-ietagra-app.web.app/',
        stuPic:'../imgs/user.png',
        CprgType:true,
    },
    {
      srNo:3,
      collegeCode:'',
      stuName:"",
      simuName:"SIMULATOR",
      discription:'DEVARSHI GUPTA',
      ref:'#',
      stuPic:'../imgs/user.png',
      CprgType:true,
  },
  {
    srNo:4,
    collegeCode:'',
    stuName:"",
    simuName:"Exam Portal",
    discription:'Deepak kumar , Raghwendra pratap singh , Shivam bhaskar , Manish Sharma',
    ref:'https://gilded-valkyrie-ae3dd2.netlify.app/',
    stuPic:'../imgs/user.png',
    CprgType:true,
},
{
  srNo:5,
  collegeCode:'',
  stuName:"",
  simuName:"INVIGILATION SYSTEM",
  discription:'AVIKAL SINGH, MUSHKAN SINGH, KARTIK VASHISHTHA,  ARCHANA MAURYA,',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:6,
  collegeCode:'',
  stuName:"",
  simuName:"NOTE SHARE APPLICATION",
  discription:'SOMESH KUMAR VERMA,PRADEEP KUMAR, GOPI CHAND AZAD,HIMANSHU SONI',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:7,
  collegeCode:'',
  stuName:"",
  simuName:"Spotify decentralised app on web3",
  discription:'TANMAY JAISWAL, VIKAS CHANDRA, VEDANSH KUMAR VISHWAKARMA, SHIVAM KUMAR PATEL',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:8,
  collegeCode:'',
  stuName:"",
  simuName:"Jarvis: Virtual AI Assistant",
  discription:'ANSHU KUMARI,SANDHYA RANI,SANIDHYAPRIYA MAURYA,YASHI LOHIYA',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:9,
  collegeCode:'',
  stuName:"",
  simuName:"TRAFFIC SIGNS RECOGNITION",
  discription:'SHUBHAM KUMAR GUPTA, MUNAZIR KHAN',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:10,
  collegeCode:'',
  stuName:"",
  simuName:"SMART ATTENDANCE SYSTEM USING FACE RECOGNITION",
  discription:'ABHISHEK KUMAR VERMA,ANKIT RAJPOOT,ANKUR,BHUVNESH YADAV',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:11,
  collegeCode:'',
  stuName:"",
  simuName:"NEWS ARTICLE SUMMARIZATION",
  discription:'SHUMAKAR PAL,MANISH KUMAR, VIKAS CHAUDHARY, PRASHANT KUMAR SINGH',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:12,
  collegeCode:'',
  stuName:"",
  simuName:"CAPTION BOT",
  discription:'KIRTI MAURYA, ADITYA PRAKASH, JYOTI VISHWAKARMA',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:13,
  collegeCode:'',
  stuName:"",
  simuName:"TEXT SUMMARIZER",
  discription:'ANSHIKA GUPTA',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:14,
  collegeCode:'',
  stuName:"",
  simuName:"IET AGRA SIMULATOR",
  discription:'AHMED RAZA, VIDIT PATSARIYA, VIVEK PAL',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:15,
  collegeCode:'',
  stuName:"",
  simuName:"Expense-Tracker--Speechly",
  discription:'PRABHAT CHAUHAN, SAURABH RAJBHAR, MONU YADAV, ANKIT PATEL',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:16,
  collegeCode:'',
  stuName:"",
  simuName:"FACE SWAPPING USING DEEP PRIVACY",
  discription:'HARSH SHRIVASTAV, JYOTI KUSHWAHA, ANIKET KUMAR, KRITIKA DHANGAR',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},
{
  srNo:17,
  collegeCode:'',
  stuName:"",
  simuName:"UDHAR BOOK KHATA",
  discription:'AMIT KUMAR YADAV, MUKUL JOSHI, KM. MALLIKA',
  ref:'#',
  stuPic:'../imgs/user.png',
  CprgType:true,
},

  
]


export {simData};
